### ISSUE TITLE
Tell us what the URL location of your route is

### ISSUE THREAD

**Issue by cspark-development** [HL-Inventory-App-Project/Inventory-App#16]
Add a new comment here to tell us the URL location of your route is and arguments it expects or provides etc so the frontend guys can use it

**Comment by Muhyidin-Abdi** [comment]
Method: GET - http://localhost:3000/api/items
Method GET - http://localhost:3000/api/items/20 { by id }
Method PUT - http://localhost:3000/api/items/20
Method DEL - http://localhost:3000/api/items/:id

**Comment by cspark-development** [comment]
Keeping this open for further documentation on other routes

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added comments above each route in the items.js file to describe the URL location, HTTP method, expected arguments, and response format for each endpoint. This will help frontend developers understand how to use these APIs.

You can review changes in this commit: https://github.com/lattaai12/HL-Inventory-App-Project-Inventory-App-16/commit/1053846c3650e1b116569267e42dd538b1e13bcd.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
